### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by jok3r69** [KovaxG/Maffia#1]
Description:

After the application was started, multiple windows showed up but the application can't be started.

Reproduce:

1. Download the application
2. Enter "Maffia-master" folder
3. Enter "Game" folder
4. Start the application with the "start_test" file
5. Observe the issue

Proof of issue
https://imgur.com/a/m7tDDBy

**Comment by KovaxG** [comment]
Yes, you can not start the application because you are missing a dependency to `network-simple`. I forgot to add it to the list of dependencies. Will add it to the file.

**Comment by KovaxG** [comment]
Updated readme.md, and added dependency install scripts, and also disabled the script that runs the multiplayer stuff.
